Revert "Run vet in a loop"
This reverts commit 850af92736cc4099528d84716e51011eb6e75c49.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -31,14 +31,13 @@ for file in ${gofiles}; do
     fi
 done
 
-for file in ${gofiles}; do
-    go vet -race ${file}
-    if [ $? -ne 0 ]; then
-        has_error=1
-    fi
-done
-
 if [ ${has_error} -ne 0 ]; then
-    echo "One or more errors. Fix them and try again."
+    echo "One or more linter errors. Fix them and try again."
     exit 1
+fi
+
+go vet -race $PWD/...
+if [ $? -ne 0 ]; then
+	echo "go vet failure, correct errors"
+	exit 1
 fi
